name: Java CI Workflow

on:
  push:
    branches:
      - main  # Trigger workflow when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Trigger workflow when a PR is made to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run on Ubuntu VM

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java 17
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Step 3: Run Maven tests
      - name: Run tests with Maven
        run: mvn test

